name: vistiq-env
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - pytorch-gpu=2.7.1
  - micro_sam=1.6.2

  - pip:
    - bioio>=3.0.0
    - bioio-lif>=1.4.1
    - bioio-tifffile>=1.3.0
    - bioio-nd2>=1.5.0
    - dask-core>=2022.3.0
    - dask-image>=0.10.0
    - napari>=0.6.6
    - napari-animation>=0.0.9
    - opencv-python-headless>=4.12.0
    - pydantic>=2.10.0
    - stackview>=0.18.0
    - scikit-image>=0.18.2
    - scipy>=1.10
    - numpy>=1.21.0
    - pandas>=1.3.1
    - prefect>=3.0.0
